---
dependencies:
  - { role: 'gparted',          tags: 'gparted' }
  - { role: 'smartmontools',    tags: ['S.M.A.R.T.', 'SMART', 'smart', 'smartmontools'] }
  - { role: 'adb',              tags: 'adb' }
