---
- name: 'Fedora: install'
  # switch to langpacks-<langcode> when Fedora 24 is released
  package: name="{{ item[1] }}-{{ item[0] }}" state=present
  with_nested:
    - "{{ langpacks }}"
    - [ 'hunspell', 'hyphen', 'mythes', 'libreoffice-langpack' ]
