---
- hosts: localhost
  remote_user: root

  vars:
    #username: user

  vars_files:
    - vars/keyboard

  tasks:
    - name: add user to %sudo
      user: name={{ username }} append=yes groups=sudo
    - name: sudo convenience
      template: mode=0400 owner=root group=root src=template/sudoers.d-convenience.j2 dest=/etc/sudoers.d/convenience
    #- name: add backports
    #  apt_repository: repo='{{ item }}'
    #  with_items:
    #  - 'deb http://ftp.no.debian.org/debian/ jessie-backports main'
    #  - 'deb-src http://ftp.no.debian.org/debian/ jessie-backports main'
    - name: boot to console, not graphical
      command: /bin/systemctl set-default multi-user.target
    - name: 'autologin getty@tty1: create directory'
      file: path='/etc/systemd/system/getty@tty1.service.d' state=directory
    - name: 'autologin getty@tty1: create service.d/.conf'
      template: src='template/getty@tty1.service.d-autologin.conf.j2' dest='/etc/systemd/system/getty@tty1.service.d/autologin.conf'

    - name: 'configure keyboard: XKBLAYOUT'
      lineinfile: dest=/etc/default/keyboard backrefs=yes regexp='(XKBLAYOUT="[^,]+)"' line='\1,no"'
    - name: 'configure keyboard: XKBVARIANT'
      lineinfile: dest=/etc/default/keyboard backrefs=yes regexp='(XKBVARIANT="[^,]+)"' line='\1,"'
    - name: 'configure keyboard: XKBOPTIONS'
      lineinfile: dest=/etc/default/keyboard backrefs=yes regexp='(XKBOPTIONS=")"' line=\\1{{ xkb_options }}\"

    - name: 'disable pcspkr (beep): rmmod'
      modprobe: name=pcspkr state=absent
    - name: 'disable pcspkr (beep): blacklist'
      template: src=template/nobeep.conf.j2 dest=/etc/modprobe.d/nobeep.conf

    - name: add grml
      apt_repository: repo='{{ item }}'
      with_items:
      - 'deb http://deb.grml.org/ grml-stable main'
      - 'deb-src http://deb.grml.org/ grml-stable main'
    - name: add grml key
      apt_key: keyserver='hkp://pool.sks-keyservers.net:11371' id=709BCE51568573EBC160E590F61E2E7CECDEA787

    - name: update APT cache
      apt: update_cache=yes
    - name: update APT (aptitude safe-upgrade)
      apt: upgrade=yes

    - name: install grml-etc
      apt: pkg=grml-etc-core state=latest

    - name: install apt-file
      apt: pkg=apt-file state=latest
      notify:
      - update apt-file cache

    - name: install vim
      apt: pkg=vim state=latest
    - name: EDITOR=vim
      template: src=template/profile.j2 dest={{ item }}
      with_items:
      - /etc/skel/.profile
      - /etc/profile.d/80_editor.sh

    - name: install zsh
      apt: pkg=zsh state=latest
    - name: set shell of user to zsh
      user: name={{ username }} shell=/bin/zsh
    - name: set shell of root to zsh
      user: name=root shell=/bin/zsh
    - name: setup ~/.zshrc.local
      template: src=template/zshrc.local.j2 dest=/etc/skel/.zshrc.local

    - name: install byobu
      apt: pkg=byobu state=latest
    - name: install chromium
      apt: pkg=chromium state=latest
    - name: install gufw
      apt: pkg=gufw state=latest
      notify:
      - enable ufw
    - name: install haveged
      apt: pkg=haveged state=latest
      notify:
      - enable and run haveged

    #- name: install Xfce
    #  apt: pkg=xfce4 state=latest
    #- name: install Xfce goodies
    #  apt: pkg=xfce4-goodies state=latest
    #- name: install Xfce whisker menu
    #  apt: pkg=xfce4-whiskermenu-plugin state=latest

    - name: propagate /etc/skel
      command: sudo -u {{ item }} sh -c 'rsync -r /etc/skel/ ~/'
      with_items:
      - "{{ username }}"
      - root

  handlers:
    - name: update apt-file cache
      command: apt-file update
    - name: enable and run haveged
      service: name=haveged state=started enabled=yes
    - name: enable ufw
      command: ufw enable
