---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - "vars/default.yml"
    - "vars/{{ ansible_distribution }}.yml"

  pre_tasks:
   #- name: group roles by distribution
   #  group_by: key=os_{{ ansible_distribution }}
   #  tags: always

  roles:
    - { role: getvars,              tags: ['always'], get: ['username'] }
    - { role: users,                tags: ['system', 'users'] }
    - { role: skel,                 tags: ['user', 'skel_pre'] }
    - { role: repos,                tags: ['system', 'pkg', 'repos'] }
    - { role: update,               tags: ['system', 'pkg', 'update'] }
   #- { role: upgrade,              tags: ['system', 'pkg', 'upgrade'] }
    - { role: conf-tools,           tags: ['system', 'user', 'conf', 'conf-tools'] }
    - { role: dns,                  tags: ['system', 'network', 'dns'] }
    - { role: auth,                 tags: ['system', 'tools', 'auth'] }
    - { role: boot,                 tags: ['system', 'boot'] }
    - { role: tty,                  tags: ['system', 'tty'] }
    - { role: keyboard,             tags: ['system', 'kbd', 'keyboard'] }
    - { role: mouse,                tags: ['system', 'touchpad', 'pointer', 'mouse'] }
    - { role: mod,                  tags: ['system', 'mod'] }
    - { role: drivers,              tags: ['system', 'drivers'] }
    - { role: init,                 tags: ['system', 'init'] }
    - { role: firewall,             tags: ['system', 'firewall'] }
    - { role: disk,                 tags: ['system', 'disk'] }
    - { role: rng,                  tags: ['system', 'rng'] }
    - { role: color,                tags: ['system', 'color'] }
    - { role: shell,                tags: ['tools', 'shell'] }
    - { role: editor,               tags: ['tools', 'editor'] }
    - { role: dev,                  tags: ['tools', 'dev'] }
    - { role: data-tools,           tags: ['tools', 'data-tools'] }
    - { role: repo-tools,           tags: ['tools', 'pkg', 'repo-tools'] }
    - { role: archive-tools,        tags: ['tools', 'archive-tools'] }
    - { role: backup,               tags: ['tools', 'backup'] }
    - { role: desktop-environment,  tags: ['system', 'de', 'desktop-environment'] }
    - { role: x-tools,              tags: ['tools', 'x', 'x-tools'] }
    - { role: terminal-emulator,    tags: ['tools', 'terminal-emulator'] }
    - { role: device-tools,         tags: ['tools', 'disk', 'device-tools'] }
    - { role: net-tools,            tags: ['tools', 'net', 'network', 'net-tools'] }
    - { role: virt,                 tags: ['tools', 'virt'] }
    - { role: web-browsers,         tags: ['tools', 'web', 'web-browsers'] }
    - { role: mail,                 tags: ['tools', 'web', 'mail'] }
    - { role: im,                   tags: ['tools', 'web', 'im'] }
    - { role: codecs,               tags: ['media', 'codecs'] }
    - { role: media-players,        tags: ['tools', 'media', 'media-players'] }
    - { role: media-editors,        tags: ['tools', 'media', 'media-editors'] }
    - { role: games,                tags: ['games'] }
    - { role: practice,             tags: ['practice'] }
    - { role: office,               tags: ['tools', 'office'] }
    - { role: fonts,                tags: ['system', 'fonts'] }
    - { role: langpacks,            tags: ['system', 'langpacks'] }
    - { role: skel,                 tags: ['user', 'skel_post', 'skel'] }
    - { role: dotfiles,             tags: ['user', 'dotfiles'] }
