---
- hosts: localhost
  connection: local
  become: true

  vars:
    #username: 

  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/default.yml"

  pre_tasks:
    #- name: group roles by distribution
    #  group_by: key=os_{{ ansible_distribution }}
    #  tags: always

    - name: get username
      set_fact:
        username: "{{ ansible_env['SUDO_USER'] }}"
      tags: always
      when: username is not defined

  roles:
    - { role: users,            tags: ['system', 'users'] }
    - { role: skel,             tags: ['user', 'skel'] }
    - { role: repos,            tags: ['system', 'pkg', 'repos'] }
    - { role: update,           tags: ['system', 'pkg', 'update'] }
   #- { role: upgrade,          tags: ['system', 'pkg', 'upgrade'] }
    - { role: dns,              tags: ['system', 'network', 'dns'] }
    - { role: sudoers,          tags: ['system', 'sudoers'] }
    - { role: boot,             tags: ['system', 'boot'] }
    - { role: tty,              tags: ['system', 'tty'] }
    - { role: keyboard,         tags: ['system', 'keyboard'] }
    - { role: mod,              tags: ['system', 'mod'] }
    - { role: drivers,          tags: ['system', 'drivers'] }
    - { role: init,             tags: ['system', 'init'] }
    - { role: firewall,         tags: ['system', 'firewall'] }
    - { role: disk,             tags: ['system', 'disk'] }
    - { role: rng,              tags: ['system', 'rng'] }
    - { role: color,            tags: ['system', 'color'] }
    - { role: shell,            tags: ['tools', 'shell'] }
    - { role: editor,           tags: ['tools', 'editor'] }
    - { role: dev,              tags: ['tools', 'dev'] }
    - { role: repo-tools,       tags: ['tools', 'pkg', 'repo-tools'] }
    - { role: cli-tools,        tags: ['tools', 'cli-tools'] }
    - { role: web-browsers,     tags: ['tools', 'web', 'web-browsers'] }
    - { role: codecs,           tags: ['media', 'codecs'] }
    - { role: media-players,    tags: ['tools', 'media', 'media-players'] }
    - { role: media-editors,    tags: ['tools', 'media', 'media-editors'] }
    - { role: office,           tags: ['tools', 'office'] }
    - { role: skel,             tags: ['user', 'skel'] }

   #- { role: dotfiles,         tags: ['user', 'dotfiles'] }
