---
- name: 'bootstrap: check if present'
  stat: path="~/.config/vcsh/repo.d/{{ dotfiles.bootstrap.name }}.git"
  become: true
  become_user: "{{ username }}"
  register: dotfiles_bootstrap_dir

# would be much cooler with some `vcsh clone --force` stuff, but in the absence of that:
- name: 'bootstrap: make space'
  file: path="{{ item }}" state=absent
  with_items:
    - '~/.bash_profile'
    - '~/.bashrc'
    - '~/.zshrc'
    - '~/.gnupg/gpg.conf'
  become: true
  become_user: "{{ username }}"
  when: dotfiles_bootstrap_dir.stat.exists == false

- name: 'bootstrap: fetch'
  command: vcsh clone "{{ dotfiles.bootstrap.url }}" "{{ dotfiles.bootstrap.name }}"
  become: true
  become_user: "{{ username }}"
  when: dotfiles_bootstrap_dir.stat.exists == false
  register: dotfiles_bootstrap

- name: 'update'
  command: mr up chdir="~"
  become: true
  become_user: "{{ username }}"
  # don't wait for update
  async: 30
  poll: 0
 #when: dotfiles_bootstrap.changed
