---
# enable when upstream X-tool bug is fixed
#xkb_options: grp:win_space_toggle,caps:escape,terminate:ctrl_alt_bksp,shift:both_capslock_cancel
xkb_options: caps:escape,terminate:ctrl_alt_bksp,shift:both_capslock_cancel
shell: /bin/zsh
EDITOR: vim
desktop_environment: i3

solarized: dark

redshift:
  temp_day: 6500
  temp_night: 3600

autolock:
  time: 30
  locker: i3lock -d

conf:
  file:
    system: /etc/xdg/system-conf
    user: .config/system-conf
  script:
    sysconf: /usr/local/bin/system-conf-sysconf
    getconf: /usr/local/bin/system-conf-getconf

dns:
  dnscrypt_proxy:
    port: 4053

dotfiles:
  bootstrap:
    url: https://github.com/aude/dotfiles
    name: aude
