---
#username: 

xkb_options: 'caps:escape,terminate:ctrl_alt_bksp,grp:lswitch,altwin:alt_super_win,shift:both_capslock_cancel'
shell: '/bin/zsh'
EDITOR: 'vim'

redshift:
  temp_day: 6500
  temp_night: 3600

#latitude: 
#longitude: 

systemd:
  user:
    run_after_x:
      directory: .config/systemd/user
      file: run-after-x.conf

dns:
  dnscrypt_proxy:
    port: 4053

dotfiles:
  bootstrap:
    url: 'https://github.com/aude/dotfiles'
    name: 'aude'
