---
- name: stop redshift
  shell: 'pkill -u "$(whoami)" redshift'
  become: true
  become_user: "{{ username }}"

- name: start redshift
  shell: 'nohup redshift -r & > /dev/null'
  become: true
  become_user: "{{ username }}"

- name: restart redshift
  command: echo a
  notify:
    - stop redshift
    - start redshift

- name: reload redshift
  command: echo a
  notify: restart redshift
