---
- name: create directory
  file: path='/etc/systemd/system/getty@tty1.service.d' state=directory
- name: create service.d/.conf
  template: src='autologin.conf.j2' dest='/etc/systemd/system/getty@tty1.service.d/autologin.conf'
