---
- name: fetch location
  uri:
    url: 'http://ipinfo.io/loc'
    return_content: yes
  register: location

- name: get latitude
  set_fact:
    latitude: "{{ location.content.split(',')[0] | trim }}"
  when: latitude is not defined

- name: get longitude
  set_fact:
    longitude: "{{ location.content.split(',')[1] | trim }}"
  when: longitude is not defined
