---
- name: 'Fedora: install'
  package: name=virt-manager state=present

- name: 'Fedora: OVMF nightlies: add repositories'
  get_url: url='https://www.kraxel.org/repos/firmware.repo' dest=/etc/yum.repos.d/kraxel-firmware.repo

- name: 'Fedora: OVMF nightlies: install'
  package: name=edk2.git-ovmf-x64 state=present
