---
- name: propagate /etc/skel
 #shell: rsync -rltu /etc/skel/ ~/
  synchronize:
    archive: no
    compress: no
    links: yes
    recursive: yes
    rsync_opts:
      - '--update'
    set_remote_user: no
    times: yes
    src: /etc/skel/
    dest: ~/
  become: yes
  become_user: "{{ item }}"
  with_items:
    - "{{ username }}"
    - root
