---
- include: freetype_{{ ansible_distribution }}.yml
- include: dejavu_{{ ansible_distribution }}.yml
- include: liberation_{{ ansible_distribution }}.yml
- include: adobe_source_code_pro_{{ ansible_distribution }}.yml
- include: google_droid_sans_{{ ansible_distribution }}.yml
- include: symbola_{{ ansible_distribution }}.yml
